site:
  title: "Modern Hybrid Infrastructure: IBM Storage Fusion & OpenShift Data Foundation"
  start_page: ibm-fusion-workshop::index.adoc

content:
  sources:
    - url: ./
      start_path: content
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    page-pagination: ""
