apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-lightspeed
  namespace: {{ .Values.lightspeed.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.lightspeed.namespace }}
