---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dcs-setup
  namespace: {{ .Values.dcsSetup.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcs-setup
  namespace: {{ .Values.dcsSetup.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dcs-setup
subjects:
  - kind: ServiceAccount
    name: dcs-setup
    namespace: {{ .Values.dcsSetup.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dcs-setup
  namespace: {{ .Values.dcsSetup.userNamespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcs-setup
  namespace: {{ .Values.dcsSetup.userNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dcs-setup
subjects:
  - kind: ServiceAccount
    name: dcs-setup
    namespace: {{ .Values.dcsSetup.namespace }}
