apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcs-setup
  namespace: {{ .Values.dcsSetup.namespace }}
  labels:
    app.kubernetes.io/name: dcs-setup
    app.kubernetes.io/component: data-ingestion
